// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFz8vYl44GlU8z0jAIGOD8RNz_irh7tI',
    appId: '1:56331451248:web:73ef6aaedb3f529e4c2db5',
    messagingSenderId: '56331451248',
    projectId: 'matematika-21de2',
    authDomain: 'matematika-21de2.firebaseapp.com',
    databaseURL: 'https://matematika-21de2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matematika-21de2.appspot.com',
    measurementId: 'G-12MHGR4C3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDS3bJxbXFG9J_WennimAZN3oYEPfOkp8',
    appId: '1:56331451248:android:604443882144b5964c2db5',
    messagingSenderId: '56331451248',
    projectId: 'matematika-21de2',
    databaseURL: 'https://matematika-21de2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matematika-21de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjPI3_bFg0iqG52uYc_5Ion2oUEI5hVM',
    appId: '1:56331451248:ios:e49e679ee5ca0fb94c2db5',
    messagingSenderId: '56331451248',
    projectId: 'matematika-21de2',
    databaseURL: 'https://matematika-21de2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matematika-21de2.appspot.com',
    iosClientId: '56331451248-ir57s3bu529b2uu21g50b2rs0gn4bka8.apps.googleusercontent.com',
    iosBundleId: 'r',
  );
}
